app:
  title: FEINA - AsyncAPI Benchmark Platform
  baseUrl: http://20.238.185.45

organization:
  name: FEINA

backend:
  baseUrl: http://20.238.185.45
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:', 'ws:', 'wss:']
    upgradeInsecureRequests: false
  cors:
    origin: http://20.238.185.45
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

proxy:
  endpoints:
    '/catalog-service':
      target: 'http://catalog-service:3001'
      changeOrigin: true
      pathRewrite:
        '^/api/proxy/catalog-service': ''
    '/scenario-service':
      target: 'http://scenario-service:3002'
      changeOrigin: true
      pathRewrite:
        '^/api/proxy/scenario-service': ''
    '/benchmark-orchestrator':
      target: 'http://benchmark-orchestrator:3003'
      changeOrigin: true
      pathRewrite:
        '^/api/proxy/benchmark-orchestrator': ''
    '/metrics-api':
      target: 'http://metrics-api:3004'
      changeOrigin: true
      pathRewrite:
        '^/api/proxy/metrics-api': ''

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters: []

permission:
  enabled: true
