apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apis-asincrones
  description: Portal Backstage per executar i comparar escenaris d'APIs asincrones.
  annotations:
    github.com/project-slug: marcfontt/apis-asincrones
    backstage.io/source-location: url:https://github.com/marcfontt/apis-asincrones
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: marcfontt
  lifecycle: experimental
