apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka-strimzi
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 1
  roles:
  - controller
  - broker
  storage:
    type: ephemeral
  resources:
    # Per obtenir resultats comparables al TFG, el broker ha de tenir QoS Guaranteed.
    # Això vol dir que requests i limits són iguals, igual que volem fer amb la
    # resta de brokers quan el desplegament està controlat pel repo.
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
