apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: apis-asincrones
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backstage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backstage
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: backstage
        image: asyncpfg65454.azurecr.io/backstage:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: production
        - name: APP_CONFIG_app_baseUrl
          value: http://pending-backstage-service-ip
        - name: APP_CONFIG_backend_baseUrl
          value: http://pending-backstage-service-ip
        - name: APP_CONFIG_backend_cors_origin
          value: http://pending-backstage-service-ip
        - name: APP_CONFIG_backend_csp_upgradeInsecureRequests
          value: "false"
        - name: APP_CONFIG_auth_environment
          value: development
        - name: APP_CONFIG_auth_providers_guest_dangerouslyAllowOutsideDevelopment
          value: "true"
        ports:
        - containerPort: 7007
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 7007
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthcheck
            port: 7007
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 384Mi
