apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  name: backstage
  namespace: apis-asincronas
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backstage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-03-16T11:49:03Z"
      labels:
        app: backstage
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: APP_CONFIG_app_baseUrl
          value: http://20.23.94.191
        - name: APP_CONFIG_backend_baseUrl
          value: http://20.23.94.191
        - name: APP_CONFIG_backend_csp_upgradeInsecureRequests
          value: "false"
        - name: APP_CONFIG_auth_environment
          value: development
        - name: APP_CONFIG_auth_providers_guest_dangerouslyAllowOutsideDevelopment
          value: "true"
        image: feinaregistry.azurecr.io/backstage:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 7007
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: backstage
        ports:
        - containerPort: 7007
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthcheck
            port: 7007
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
