apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-orchestrator
  namespace: apis-asincrones
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: benchmark-orchestrator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: benchmark-orchestrator
    spec:
      serviceAccountName: benchmark-orchestrator
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: benchmark-orchestrator
        image: asyncpfg65454.azurecr.io/benchmark-orchestrator:latest
        imagePullPolicy: Always
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: PORT
          value: "3003"
        - name: NAMESPACE
          value: apis-asincrones
        - name: BROKER_NAMESPACE
          value: brokers
        - name: SCENARIO_SERVICE_URL
          value: http://scenario-service:3002
        - name: METRICS_API_URL
          value: http://metrics-api:3004
        - name: ACR_SERVER
          value: asyncpfg65454.azurecr.io
        - name: LOAD_GENERATOR_CPU
          value: 100m
        - name: MAX_CONCURRENT_RUNS
          value: "1"
        - name: LOAD_GENERATOR_NODE_SELECTOR_KEY
          value: benchmark-role
        - name: LOAD_GENERATOR_NODE_SELECTOR_VALUE
          value: loadgen
        - name: KAFKA_BROKERS
          value: kafka-cluster-kafka-bootstrap.brokers.svc.cluster.local:9092
        - name: CONFLUENT_BROKERS
          value: kafka-cluster-kafka-bootstrap.brokers.svc.cluster.local:9092
        - name: NATS_BROKER_URL
          value: nats://nats.brokers.svc.cluster.local:4222
        - name: RABBITMQ_URL
          value: amqp://admin:BenchmarkAdmin2024@rabbitmq.brokers.svc.cluster.local:5672
        ports:
        - containerPort: 3003
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 192Mi
          requests:
            cpu: 25m
            memory: 96Mi
