apiVersion: apps/v1
kind: Deployment
metadata:
  name: scenario-service
  namespace: apis-asincrones
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: scenario-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scenario-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: scenario-service
        image: asyncpfgpayg65454.azurecr.io/scenario-service:latest
        imagePullPolicy: Always
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: PORT
          value: "3002"
        ports:
        - containerPort: 3002
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 192Mi
          requests:
            cpu: 25m
            memory: 96Mi
