apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"benchmark-orchestrator","namespace":"apis-asincronas"},"spec":{"ports":[{"port":3003,"targetPort":3003}],"selector":{"app":"benchmark-orchestrator"},"type":"ClusterIP"}}
  name: benchmark-orchestrator
  namespace: apis-asincronas
spec:
  clusterIP: 10.0.151.118
  clusterIPs:
  - 10.0.151.118
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: benchmark-orchestrator
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
