apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"catalog-service","namespace":"apis-asincronas"},"spec":{"ports":[{"port":3001,"targetPort":3001}],"selector":{"app":"catalog-service"},"type":"ClusterIP"}}
  name: catalog-service
  namespace: apis-asincronas
spec:
  clusterIP: 10.0.176.14
  clusterIPs:
  - 10.0.176.14
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: catalog-service
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
