apiVersion: v1
kind: Service
metadata:
  name: scenario-service
  namespace: apis-asincronas
spec:
  type: ClusterIP
  selector:
    app: scenario-service
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
