apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"scenario-service","namespace":"apis-asincronas"},"spec":{"ports":[{"port":3002,"targetPort":3002}],"selector":{"app":"scenario-service"},"type":"ClusterIP"}}
  name: scenario-service
  namespace: apis-asincronas
spec:
  clusterIP: 10.0.94.13
  clusterIPs:
  - 10.0.94.13
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: scenario-service
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
